# SPDX-License-Identifier: MIT
---
# Put internal variables here with values for unrecognized distributions.

__nbde_client_package_list: []
__nbde_client_initramfs_update_cmd: ""

# vim:set ts=2 sw=2 et:
