---
- hosts: all

  vars:
    nbde_client_bindings:
      - device: /dev/sda1
        # recommend vault encrypting the passphrase
        # see https://docs.ansible.com/ansible/latest/user_guide/vault.html
        passphrase: password
        servers:
          - http://server1.example.com
          - http://server2.example.com
  roles:
    - linux-system-roles.nbde_client
# vim:set ts=2 sw=2 et:
