---
- hosts: all

  vars:
    nbde_client_bindings:
      - device: /dev/sda1
        pass: password
        slot: 2
        state: absent

  roles:
    - linux-system-roles.nbde_client
# vim:set ts=2 sw=2 et:
