---
- hosts: all
  become: true

  vars:
    nbde_client_bindings:
      - devices:
          - path: /tmp/sda1
            pass: password
        pin:
          slot: 2
        state: absent

  roles:
    - linux-system-roles.nbde_client
# vim:set ts=2 sw=2 et:
